### ISSUE TITLE
Falta la parte del palindromo

### ISSUE THREAD

**Issue by jramirezl** [mateohernandezs/TareaStringExcepciones#1]
https://github.com/mateohernandezs/TareaStringExcepciones/blob/f536f538725ca0ca3bdcbe00def91736e17a7e96/src/com/bancodebogota/fdm/tareastringexcepciones/Main.java#L73

**Comment by mateohernandezs** [comment]
Profe la parte del palindromo si está, en las lineas 80 y 81 está el llamado a los metodos desde el main. O a que se refiere profe?
